name: 'Run squawk'
description: '🦉 Run squawk to lint PostgreSQL migrations'
author: 'K-Phoen'

inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}

  targets:
    description: |
      Pattern describing what files to lint.
      See https://github.com/isaacs/minimatch for valid patterns.
      Default is 'migrations/*.sql'.
    default: 'migrations/*.sql'

  exclude:
    description: |
      Comma-separated checks to exclude (--exclude flag from squawk).
      Default is empty.
    default: ''
  
  reporter:
    description: |
      Reporter of reviewdog command (`-reporter` flag from [reviewdog](https://github.com/reviewdog/reviewdog)).
      Default is 'github-pr-review'.
    default: 'github-pr-review'
  
  squawk_version:
    description: |
      The squawk version to use.
      Default is 'v0.8.2'.
    default: v0.8.2
  
  reviewdog_version:
    description: |
      The reviewdog version to use.
      Default is '0.14.0'.
    default: '0.14.0'

runs:
  using: node16
  main: dist/index.js

branding:
  icon: "database"
  color: "blue"